---
title: "Seonggyu's Projects & Publications"
author: Seonggyu Park
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1VIk_ov2KU34-eayiOAJqeci-3m3tumNiVMqlCfIKCjM/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Main
================================================================================

Seonggyu Park {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<!-- Education {data-icon=graduation-cap data-concise=true} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('education') -->
<!-- ``` -->
<!-- <br> -->
<!-- <br> -->

<!-- Research Experience {data-icon=flask} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('research_experiences') -->
<!-- ``` -->


Projects {data-icon=project-diagram}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('projects')
```

<br>
<br>
<br>
<br>
<br>


Publications {data-icon=copy}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('publications')
```



Training Manuals {data-icon=file-invoice}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('manuals')
```


<br>
<br>


Conference Proceedings {data-icon=users}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('conference')
```


<!-- Invited Talks {data-icon=chalkboard-teacher} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('invited_talks') -->
<!-- ``` -->


Workshops Conducted {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('workshops')
```



<!-- Fellowships and awards {data-icon=trophy} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('awards') -->
<!-- ``` -->



Software Development {data-icon=magic}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('software')
```



<!-- Teaching Experience {data-icon=chalkboard-teacher} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('teachings') -->
<!-- ``` -->



<!-- ```{r} -->
<!-- CV %<>% print_links() -->
<!-- ``` -->

